contact_phone_unknown1 = "DESCRIPTION NEEDED FORcontact_phone_unknown1"
district_city_council_district = "DESCRIPTION NEEDED FORdistrict_city_council_district"
district_city_incorporation = "DESCRIPTION NEEDED FORdistrict_city_incorporation"
district_city_limits = "DESCRIPTION NEEDED FORdistrict_city_limits"
district_city_municipality = "DESCRIPTION NEEDED FORdistrict_city_municipality"
district_city_name = "DESCRIPTION NEEDED FORdistrict_city_name"
district_city_school_district = "DESCRIPTION NEEDED FORdistrict_city_school_district"
district_county_career_center = "DESCRIPTION NEEDED FORdistrict_county_career_center"
district_county_commissioner_precinct = "DESCRIPTION NEEDED FORdistrict_county_commissioner_precinct"
district_county_community_college = "DESCRIPTION NEEDED FORdistrict_county_community_college"
district_county_constable_precinct = "DESCRIPTION NEEDED FORdistrict_county_constable_precinct"
district_county_district_attorney = "DESCRIPTION NEEDED FORdistrict_county_district_attorney"
district_county_education_service_center = "DESCRIPTION NEEDED FORdistrict_county_education_service_center"
district_county_exempted_village_school_district = "DESCRIPTION NEEDED FORdistrict_county_exempted_village_school_district"
district_county_first_class_school = "DESCRIPTION NEEDED FORdistrict_county_first_class_school"
district_county_id = "DESCRIPTION NEEDED FORdistrict_county_id"
district_county_library_district = "DESCRIPTION NEEDED FORdistrict_county_library_district"
district_county_local_school_district = "DESCRIPTION NEEDED FORdistrict_county_local_school_district"
district_county_mass_transit_authority = "DESCRIPTION NEEDED FORdistrict_county_mass_transit_authority"
district_county_name = "DESCRIPTION NEEDED FORdistrict_county_name"
district_county_number = "DESCRIPTION NEEDED FORdistrict_county_number"
district_county_representational_school = "DESCRIPTION NEEDED FORdistrict_county_representational_school"
district_county_sanitary = "DESCRIPTION NEEDED FORdistrict_county_sanitary"
district_county_school = "DESCRIPTION NEEDED FORdistrict_county_school"
district_county_school_district = "DESCRIPTION NEEDED FORdistrict_county_school_district"
district_county_sub_school_district = "DESCRIPTION NEEDED FORdistrict_county_sub_school_district"
district_county_supervisory = "DESCRIPTION NEEDED FORdistrict_county_supervisory"
district_county_technical_college = "DESCRIPTION NEEDED FORdistrict_county_technical_college"
district_county_township = "DESCRIPTION NEEDED FORdistrict_county_township"
district_county_village = "DESCRIPTION NEEDED FORdistrict_county_village"
district_county_ward = "DESCRIPTION NEEDED FORdistrict_county_ward"
district_county_water_district_01 = "DESCRIPTION NEEDED FORdistrict_county_water_district_01"
district_county_water_district_02 = "DESCRIPTION NEEDED FORdistrict_county_water_district_02"
district_court_appeallate = "DESCRIPTION NEEDED FORdistrict_court_appeallate"
district_court_county = "DESCRIPTION NEEDED FORdistrict_court_county"
district_court_municipal = "DESCRIPTION NEEDED FORdistrict_court_municipal"
district_federal_congressional = "DESCRIPTION NEEDED FORdistrict_federal_congressional"
district_state = "DESCRIPTION NEEDED FORdistrict_state"
district_state_board_of_education = "DESCRIPTION NEEDED FORdistrict_state_board_of_education"
district_state_circuit_court = "DESCRIPTION NEEDED FORdistrict_state_circuit_court"
district_state_court_of_appeals = "DESCRIPTION NEEDED FORdistrict_state_court_of_appeals"
district_state_district_combo = "DESCRIPTION NEEDED FORdistrict_state_district_combo"
district_state_juristidction = "DESCRIPTION NEEDED FORdistrict_state_juristidction"
district_state_legislative_lower = "DESCRIPTION NEEDED FORdistrict_state_legislative_lower"
district_state_legislative_upper = "DESCRIPTION NEEDED FORdistrict_state_legislative_upper"
district_state_lower = "DESCRIPTION NEEDED FORdistrict_state_lower"
district_state_multijurisdictional_judge = "DESCRIPTION NEEDED FORdistrict_state_multijurisdictional_judge"
district_state_upper = "DESCRIPTION NEEDED FORdistrict_state_upper"
file_origin = "DESCRIPTION NEEDED FORfile_origin"
mail_address1 = "DESCRIPTION NEEDED FORmail_address1"
mail_address2 = "DESCRIPTION NEEDED FORmail_address2"
mail_change_date = "DESCRIPTION NEEDED FORmail_change_date"
mail_city = "DESCRIPTION NEEDED FORmail_city"
mail_country = "DESCRIPTION NEEDED FORmail_country"
mail_postal_code = "DESCRIPTION NEEDED FORmail_postal_code"
mail_standardized = "DESCRIPTION NEEDED FORmail_standardized"
mail_state = "DESCRIPTION NEEDED FORmail_state"
mail_zip4 = "DESCRIPTION NEEDED FORmail_zip4"
mail_zip5 = "DESCRIPTION NEEDED FORmail_zip5"
person_dob = "DESCRIPTION NEEDED FORperson_dob"
person_gender = "DESCRIPTION NEEDED FORperson_gender"
person_name_first = "DESCRIPTION NEEDED FORperson_name_first"
person_name_last = "DESCRIPTION NEEDED FORperson_name_last"
person_name_middle = "DESCRIPTION NEEDED FORperson_name_middle"
person_name_prefix = "DESCRIPTION NEEDED FORperson_name_prefix"
person_name_suffix = "DESCRIPTION NEEDED FORperson_name_suffix"
residence_address1 = "DESCRIPTION NEEDED FORresidence_address1"
residence_address2 = "DESCRIPTION NEEDED FORresidence_address2"
residence_address_id = "DESCRIPTION NEEDED FORresidence_address_id"
residence_city = "DESCRIPTION NEEDED FORresidence_city"
residence_country = "DESCRIPTION NEEDED FORresidence_country"
residence_effective_date = "DESCRIPTION NEEDED FORresidence_effective_date"
residence_part_city = "DESCRIPTION NEEDED FORresidence_part_city"
residence_part_house_direction = "DESCRIPTION NEEDED FORresidence_part_house_direction"
residence_part_house_number = "DESCRIPTION NEEDED FORresidence_part_house_number"
residence_part_number = "DESCRIPTION NEEDED FORresidence_part_number"
residence_part_number_suffix = "DESCRIPTION NEEDED FORresidence_part_number_suffix"
residence_part_state = "DESCRIPTION NEEDED FORresidence_part_state"
residence_part_street_direction = "DESCRIPTION NEEDED FORresidence_part_street_direction"
residence_part_street_name = "DESCRIPTION NEEDED FORresidence_part_street_name"
residence_part_street_number = "DESCRIPTION NEEDED FORresidence_part_street_number"
residence_part_street_post_type = "DESCRIPTION NEEDED FORresidence_part_street_post_type"
residence_part_street_pre_directional = "DESCRIPTION NEEDED FORresidence_part_street_pre_directional"
residence_part_street_suffix = "DESCRIPTION NEEDED FORresidence_part_street_suffix"
residence_part_street_type = "DESCRIPTION NEEDED FORresidence_part_street_type"
residence_part_unit_number = "DESCRIPTION NEEDED FORresidence_part_unit_number"
residence_part_unit_type = "DESCRIPTION NEEDED FORresidence_part_unit_type"
residence_part_zip4 = "DESCRIPTION NEEDED FORresidence_part_zip4"
residence_part_zip5 = "DESCRIPTION NEEDED FORresidence_part_zip5"
residence_parts_house_number = "DESCRIPTION NEEDED FORresidence_parts_house_number"
residence_parts_street_name = "DESCRIPTION NEEDED FORresidence_parts_street_name"
residence_parts_unit_number = "DESCRIPTION NEEDED FORresidence_parts_unit_number"
residence_parts_unit_type = "DESCRIPTION NEEDED FORresidence_parts_unit_type"
residence_postal_code = "DESCRIPTION NEEDED FORresidence_postal_code"
residence_standardized = "DESCRIPTION NEEDED FORresidence_standardized"
residence_state = "DESCRIPTION NEEDED FORresidence_state"
residence_zip4 = "DESCRIPTION NEEDED FORresidence_zip4"
residence_zip5 = "DESCRIPTION NEEDED FORresidence_zip5"
voter_absentee = "DESCRIPTION NEEDED FORvoter_absentee"
voter_county = "DESCRIPTION NEEDED FORvoter_county"
voter_political_party = "DESCRIPTION NEEDED FORvoter_political_party"
voter_precinct_code = "DESCRIPTION NEEDED FORvoter_precinct_code"
voter_precinct_name = "DESCRIPTION NEEDED FORvoter_precinct_name"
voter_precinct_number = "DESCRIPTION NEEDED FORvoter_precinct_number"
voter_precinct_split = "DESCRIPTION NEEDED FORvoter_precinct_split"
voter_registration_application_source = "DESCRIPTION NEEDED FORvoter_registration_application_source"
voter_registration_date = "DESCRIPTION NEEDED FORvoter_registration_date"
voter_registration_permanent_absentee = "DESCRIPTION NEEDED FORvoter_registration_permanent_absentee"
voter_registration_status = "DESCRIPTION NEEDED FORvoter_registration_status"
voter_registration_status_reason = "DESCRIPTION NEEDED FORvoter_registration_status_reason"
voter_registration_type = "DESCRIPTION NEEDED FORvoter_registration_type"
voter_vuid = "DESCRIPTION NEEDED FORvoter_vuid"
