voter_vuid = [ "VUIDNO", "VUID", "VOTER REG NUMBER", "SOS_VOTERID", "VTRID",]
voter_registration_date = [ "REGISTRATIONDATE", "REGISTRATION_DATE", "EDR", "VOTE_ELIGIBLE_DATE", "EDRDAT",]
voter_registration_status = [ "VOTER STATUS", "STATUS", "VOTER_STATUS",]
voter_registration_status_reason = [ "VOTER_STATUS_REASON", "VOTER STATUS REASON",]
voter_precinct_number = [ "PRECINCT_CODE", "PREC_CODE", "PCT",]
voter_precinct_name = [ "PRECINCT", "PCTNAME", "PRECINCT_NAME",]
voter_absentee = [ "ABSENTEE",]
person_name_first = [ "FIRST_NAME", "FSTNAM", "FIRSTNAME", "FNAME",]
person_name_middle = [ "MIDDLE_NAME", "MNAME", "MIDDLENAME", "MIDNAM",]
person_name_last = [ "LSTNAM", "LAST_NAME", "LNAME", "LASTNAME",]
person_dob = [ "DATE_OF_BIRTH", "DOB",]
residence_standardized = [ "RESIDENCEADDRESS",]
residence_part_house_number = [ "RA_HS_NUM",]
residence_part_house_direction = [ "RA_STDIR_CODE",]
residence_part_street_name = [ "RA_STREET_NAME", "STRNAM", "RSTNAME",]
residence_part_street_type = [ "STRTYP", "RSTTYPE", "RA_STTYPE",]
residence_part_street_suffix = [ "RA_STDIR_CODE_POST",]
residence_part_unit_number = [ "RA_UNIT_NUM", "UNITNO", "RUNUM",]
residence_part_unit_type = [ "UNITYP", "RA_UTYP_CODE", "RUTYPE",]
residence_part_city = [ "RCITY", "RA_CITY", "RSCITY",]
residence_part_state = [ "RA_STATE", "RSTATE",]
residence_part_zip5 = [ "RZIP", "RA_ZIP_CODE", "RZIPCD",]
mail_address1 = [ "MAILING_ADDRESS1", "MA_ADDR_LINE_1", "MLADD1", "MAILINGADDRESS1", "MADR1",]
mail_city = [ "MAILING_CITY", "MAILINGCITYSTATEZIP", "MA_CITY", "MCITY", "MLCITY",]
mail_state = [ "MST", "MLSTAT", "MA_STATE", "MAILING_STATE",]
mail_zip5 = [ "MA_ZIP_CODE", "MZIP", "MLZIPCD", "MAILING_ZIP",]
mail_zip4 = [ "MA_ZIP_PLUS", "MZIP+4", "MAILING_ZIP_PLUS4",]
mail_standardized = [ "MAILINGADDRESS",]
district_city_limits = [ "CITY_LIMITS",]
district_county_number = [ "COUNTY_NUMBER", "CURRENT_COUNTY",]
district_county_ward = [ "ward", "WARD",]
district_state_legislative_lower = [ "HOUSE_DISTRICT", "STATE_REPRESENTATIVE_DISTRICT", "DIST03", "NEWHD",]
district_state_legislative_upper = [ "STATE_SENATE_DISTRICT", "DIST02", "SENATE_DISTRICT", "NEWSD",]
district_federal_congressional = [ "NEWCD", "DIST01", "CONGRESSIONAL", "CONGRESSIONAL_DISTRICT", "CONGRESS_DISTRICT",]
contact_phone_unknown1 = [ "PHONE_NO", "PHONENUMBER",]
voter_precinct_code = [ "PCTCOD",]
voter_precinct_split = [ "PCTSPT",]
person_gender = [ "GENDER", "SEX",]
person_name_prefix = [ "NAMPFX",]
residence_part_street_number = [ "BLKNUM",]
residence_part_street_pre_directional = [ "STRPRE",]
residence_part_street_direction = [ "STRDIR",]
residence_part_zip4 = [ "RZIP+4",]
residence_address_id = [ "ADDRID",]
residence_effective_date = [ "REFDAT",]
mail_address2 = [ "MAILINGADDRESS2", "MAILING_SECONDARY_ADDRESS", "MLADD2", "MADR2",]
mail_country = [ "MLCTRY", "MAILING_COUNTRY",]
mail_change_date = [ "MCHGDT",]
district_county_commissioner_precinct = [ "DIST04",]
district_city_municipality = [ "MUNICIPALITY", "DIST05",]
district_county_constable_precinct = [ "DIST06",]
district_county_school_district = [ "DIST07",]
district_county_sub_school_district = [ "DIST08",]
district_county_water_district_01 = [ "DIST11",]
district_county_mass_transit_authority = [ "DIST12",]
district_county_water_district_02 = [ "DIST13",]
district_state_board_of_education = [ "DIST16", "STATE_BOARD_OF_EDUCATION",]
district_county_community_college = [ "DIST18",]
district_city_council_district = [ "DIST19",]
voter_political_party = [ "PARTY_AFFILIATION",]
person_name_suffix = [ "SUFFIX", "SFX",]
residence_address1 = [ "RESIDENTIAL_ADDRESS1", "ADDRESS1",]
residence_address2 = [ "RESIDENTIAL_SECONDARY_ADDR", "ADDRESS2",]
residence_city = [ "RESIDENTIAL_CITY", "ADDRESSCITY",]
residence_state = [ "RESIDENTIAL_STATE", "ADDRESSSTATE",]
residence_zip5 = [ "RESIDENTIAL_ZIP", "ADDRESSZIP",]
residence_zip4 = [ "RESIDENTIAL_ZIP_PLUS4",]
residence_country = [ "RESIDENTIAL_COUNTRY",]
residence_postal_code = [ "RESIDENTIAL_POSTALCODE",]
mail_postal_code = [ "MAILING_POSTAL_CODE",]
district_court_municipal = [ "MUNICIPAL_COURT_DISTRICT",]
district_court_county = [ "COUNTY_COURT_DISTRICT",]
district_court_appeallate = [ "COURT_OF_APPEALS",]
district_city_name = [ "CITY",]
district_city_school_district = [ "CITY_SCHOOL_DISTRICT",]
district_county_id = [ "COUNTY_ID",]
district_county_township = [ "TOWNSHIP",]
district_county_village = [ "VILLAGE",]
district_county_local_school_district = [ "LOCAL_SCHOOL_DISTRICT",]
district_county_library_district = [ "LIBRARY",]
district_county_career_center = [ "CAREER_CENTER",]
district_county_education_service_center = [ "EDU_SERVICE_CENTER_DISTRICT",]
district_county_exempted_village_school_district = [ "EXEMPTED_VILL_SCHOOL_DISTRICT",]
voter_county = [ "COUNTY",]
residence_part_number = [ "RHNUM",]
residence_part_number_suffix = [ "RDESIG",]
residence_part_street_post_type = [ "RSTSFX",]
file_origin = [ "FILE_ORIGIN",]
voter_registration_application_source = [ "APPLICATION SOURCE",]
voter_registration_permanent_absentee = [ "IS PERMANENT ABSENTEE",]
voter_registration_type = [ "VOTER TYPE",]
residence_parts_house_number = [ "HOUSENUMBER",]
residence_parts_street_name = [ "STREETNAME",]
residence_parts_unit_type = [ "UNITTYPE",]
residence_parts_unit_number = [ "UNITNUMBER",]
district_state_juristidction = [ "JURISDICTION",]
district_state_district_combo = [ "DISTRICTCOMBO",]
district_state_upper = [ "STATE SENATE",]
district_state_lower = [ "STATE ASSEMBLY",]
district_state_court_of_appeals = [ "COURT OF APPEALS",]
district_state_multijurisdictional_judge = [ "MULTI-JURISDICTIONAL JUDGE",]
district_county_name = [ "COUNTY",]
district_county_supervisory = [ "COUNTY SUPERVISORY",]
district_county_school = [ "SCHOOL",]
district_county_sanitary = [ "SANITARY",]
district_county_technical_college = [ "TECHNICAL COLLEGE",]
district_county_representational_school = [ "REPRESENTATIONAL SCHOOL",]
district_state = [ "STATE",]
district_county_district_attorney = [ "DISTRICT ATTORNEY",]
district_state_circuit_court = [ "CIRCUIT COURT",]
district_county_first_class_school = [ "FIRST CLASS SCHOOL",]
district_city_incorporation = [ "INCORPORATION",]
