contact_phone_unknown1 = "Phone number"
district_city_council_district = "City council district number"
district_city_incorporation = "City incorporation status"
district_city_limits = "City limits of a district"
district_city_municipality = "City or municipality name"
district_city_name = "City in a US congressional district"
district_city_school_district = "City of a school district"
district_county_career_center = "Location of a career center"
district_county_commissioner_precinct = "Precinct number within a commissioner district"
district_county_community_college = "School level"
district_county_constable_precinct = "Precinct within a district where a constable is elected."
district_county_district_attorney = "Office of the District Attorney at the county level"
district_county_education_service_center = "Name of the education service center at the county level"
district_county_exempted_village_school_district = "Village school district status"
district_county_first_class_school = "School level"
district_county_id = "County ID"
district_county_library_district = "Library district"
district_county_local_school_district = "Local school district name"
district_county_mass_transit_authority = "Mass transit authority at the state or local level"
district_county_name = "County name"
district_county_number = "County identifier"
district_county_representational_school = "Type of school"
district_county_sanitary = "Type of sanitary district"
district_county_school = "School district or county name"
district_county_school_district = "School district name"
district_county_sub_school_district = "School district level"
district_county_supervisory = "Supervisory district at the county level"
district_county_technical_college = "Type of institution"
district_county_township = "Voter registration locality - TOWNSHIP"
district_county_village = "Village name"
district_county_ward = "Local government division"
district_county_water_district_01 = "Water district level 1"
district_county_water_district_02 = "Water district level 2"
district_court_appeallate = "Court level"
district_court_county = "Court county name"
district_court_municipal = "Court level within a municipality"
district_federal_congressional = "US Congressional district number or abbreviation"
district_state = "State or county where a voter is registered."
district_state_board_of_education = "State board of education for a school district"
district_state_circuit_court = "Court level (e.g. CIRCUIT COURT)"
district_state_court_of_appeals = "Court level"
district_state_district_combo = "State and county combination"
district_state_juristidction = "State or local government jurisdiction"
district_state_legislative_lower = "State legislative district number"
district_state_legislative_upper = "State legislative district number"
district_state_lower = "State assembly district name"
district_state_multijurisdictional_judge = "District judge in a multi-jurisdictional state"
district_state_upper = "State legislative district"
file_origin = "DESCRIPTION NEEDED FORfile_origin"
mail_address1 = " mailing address line 1"
mail_address2 = " mailing secondary address"
mail_change_date = "Date of last address change"
mail_city = "City name for mailing purposes"
mail_country = "Country of mailing address"
mail_postal_code = "Postal code of a mailing address"
mail_standardized = " mailing address"
mail_state = "State or region where voter is registered"
mail_zip4 = "US ZIP code with 4 digits"
mail_zip5 = "US mailing zip code"
person_dob = "Date of birth"
person_gender = "Gender type"
person_name_first = "First name of a person"
person_name_last = "Last name of a person"
person_name_middle = "Middle name of a person"
person_name_prefix = "Prefix of a person's name"
person_name_suffix = "Suffix of a person's name"
residence_address1 = "Residential street address"
residence_address2 = "Street address or PO box of secondary home"
residence_address_id = "Unique identifier for a residence address"
residence_city = "City of residence"
residence_country = "Country of residence"
residence_effective_date = "Date of effective residency"
residence_part_city = "City in state abbreviation format"
residence_part_house_direction = "Direction of the house part at a residence"
residence_part_house_number = "House number of a part of a residence"
residence_part_number = "Residence part number"
residence_part_number_suffix = "Type of suffix used in residence part numbers"
residence_part_state = "State of residence"
residence_part_street_direction = "Direction of street at residence part"
residence_part_street_name = "Street name at a residence"
residence_part_street_number = "Street number of a residence"
residence_part_street_post_type = "Type of street address suffix"
residence_part_street_pre_directional = "Street name before a directional suffix (e.g. 'Main St' before 'N')"
residence_part_street_suffix = "Street suffix (e.g. ST, AVE, RD)"
residence_part_street_type = "Street type at a residential address"
residence_part_unit_number = "Residence part unit number"
residence_part_unit_type = "Type of residence part unit"
residence_part_zip4 = "US Zip Code (Zip + 4)"
residence_part_zip5 = "US Zip Code"
residence_parts_house_number = "House number"
residence_parts_street_name = "Street name of a residence"
residence_parts_unit_number = "Apartment or unit number"
residence_parts_unit_type = "Type of unit in a residence"
residence_postal_code = "Postal code of a residential address"
residence_standardized = "Street address of the voter"
residence_state = "State where voter resides"
residence_zip4 = "US Zip Code plus 4 digit extension"
residence_zip5 = "US Zip Code"
voter_absentee = "Absentee voting status"
voter_county = "County where a person is registered to vote"
voter_political_party = "Voter political party affiliation"
voter_precinct_code = "Precinct code"
voter_precinct_name = "Voter precinct name or number"
voter_precinct_number = "Voter precinct number (e.g. state, county, city)"
voter_precinct_split = "Voter precinct split"
voter_registration_application_source = "Application source for voter registration"
voter_registration_date = "Date of voter registration"
voter_registration_permanent_absentee = "Voter registration status for permanent absentee voting"
voter_registration_status = "Voter registration status"
voter_registration_status_reason = "VOTER STATUS REASON"
voter_registration_type = "Voter registration type"
voter_vuid = "Voter identification number"
