voter_vuid = [ "VOTER REG NUMBER", "SOS_VOTERID", "VUID", "VTRID", "VUIDNO",]
voter_registration_date = [ "VOTE_ELIGIBLE_DATE", "REGISTRATION_DATE", "EDRDAT", "REGISTRATIONDATE", "EDR",]
voter_registration_status = [ "VOTER STATUS", "STATUS", "VOTER_STATUS",]
voter_registration_status_reason = [ "VOTER STATUS REASON", "VOTER_STATUS_REASON",]
voter_precinct_number = [ "PREC_CODE", "PCT", "PRECINCT_CODE",]
voter_precinct_name = [ "PRECINCT", "PRECINCT_NAME", "PCTNAME",]
voter_absentee = [ "ABSENTEE",]
person_name_first = [ "FNAME", "FIRST_NAME", "FSTNAM", "FIRSTNAME",]
person_name_middle = [ "MIDNAM", "MIDDLE_NAME", "MIDDLENAME", "MNAME",]
person_name_last = [ "LNAME", "LAST_NAME", "LASTNAME", "LSTNAM",]
person_dob = [ "DOB", "DATE_OF_BIRTH",]
residence_standardized = [ "RESIDENCEADDRESS",]
residence_part_house_number = [ "RA_HS_NUM",]
residence_part_house_direction = [ "RA_STDIR_CODE",]
residence_part_street_name = [ "STRNAM", "RA_STREET_NAME", "RSTNAME",]
residence_part_street_type = [ "STRTYP", "RA_STTYPE", "RSTTYPE",]
residence_part_street_suffix = [ "RA_STDIR_CODE_POST",]
residence_part_unit_number = [ "RUNUM", "RA_UNIT_NUM", "UNITNO",]
residence_part_unit_type = [ "RUTYPE", "RA_UTYP_CODE", "UNITYP",]
residence_part_city = [ "RA_CITY", "RSCITY", "RCITY",]
residence_part_state = [ "RSTATE", "RA_STATE",]
residence_part_zip5 = [ "RZIPCD", "RA_ZIP_CODE", "RZIP",]
mail_address1 = [ "MA_ADDR_LINE_1", "MAILING_ADDRESS1", "MLADD1", "MADR1", "MAILINGADDRESS1",]
mail_city = [ "MA_CITY", "MCITY", "MLCITY", "MAILINGCITYSTATEZIP", "MAILING_CITY",]
mail_state = [ "MLSTAT", "MST", "MAILING_STATE", "MA_STATE",]
mail_zip5 = [ "MA_ZIP_CODE", "MAILING_ZIP", "MLZIPCD", "MZIP",]
mail_zip4 = [ "MAILING_ZIP_PLUS4", "MZIP+4", "MA_ZIP_PLUS",]
mail_standardized = [ "MAILINGADDRESS",]
district_city_limits = [ "CITY_LIMITS",]
district_county_number = [ "COUNTY_NUMBER", "CURRENT_COUNTY",]
district_county_ward = [ "WARD", "ward",]
district_state_legislative_lower = [ "STATE_REPRESENTATIVE_DISTRICT", "NEWHD", "HOUSE_DISTRICT", "DIST03",]
district_state_legislative_upper = [ "NEWSD", "SENATE_DISTRICT", "DIST02", "STATE_SENATE_DISTRICT",]
district_federal_congressional = [ "NEWCD", "CONGRESS_DISTRICT", "CONGRESSIONAL", "CONGRESSIONAL_DISTRICT", "DIST01",]
contact_phone_unknown1 = [ "PHONE_NO", "PHONENUMBER",]
voter_precinct_code = [ "PCTCOD",]
voter_precinct_split = [ "PCTSPT",]
person_gender = [ "GENDER", "SEX",]
person_name_prefix = [ "NAMPFX",]
residence_part_street_number = [ "BLKNUM",]
residence_part_street_pre_directional = [ "STRPRE",]
residence_part_street_direction = [ "STRDIR",]
residence_part_zip4 = [ "RZIP+4",]
residence_address_id = [ "ADDRID",]
residence_effective_date = [ "REFDAT",]
mail_address2 = [ "MAILINGADDRESS2", "MLADD2", "MAILING_SECONDARY_ADDRESS", "MADR2",]
mail_country = [ "MAILING_COUNTRY", "MLCTRY",]
mail_change_date = [ "MCHGDT",]
district_county_commissioner_precinct = [ "DIST04",]
district_city_municipality = [ "DIST05", "MUNICIPALITY",]
district_county_constable_precinct = [ "DIST06",]
district_county_school_district = [ "DIST07",]
district_county_sub_school_district = [ "DIST08",]
district_county_water_district_01 = [ "DIST11",]
district_county_mass_transit_authority = [ "DIST12",]
district_county_water_district_02 = [ "DIST13",]
district_state_board_of_education = [ "DIST16", "STATE_BOARD_OF_EDUCATION",]
district_county_community_college = [ "DIST18",]
district_city_council_district = [ "DIST19",]
voter_political_party = [ "PARTY_AFFILIATION",]
person_name_suffix = [ "SUFFIX", "SFX",]
residence_address1 = [ "ADDRESS1", "RESIDENTIAL_ADDRESS1",]
residence_address2 = [ "ADDRESS2", "RESIDENTIAL_SECONDARY_ADDR",]
residence_city = [ "ADDRESSCITY", "RESIDENTIAL_CITY",]
residence_state = [ "RESIDENTIAL_STATE", "ADDRESSSTATE",]
residence_zip5 = [ "RESIDENTIAL_ZIP", "ADDRESSZIP",]
residence_zip4 = [ "RESIDENTIAL_ZIP_PLUS4",]
residence_country = [ "RESIDENTIAL_COUNTRY",]
residence_postal_code = [ "RESIDENTIAL_POSTALCODE",]
mail_postal_code = [ "MAILING_POSTAL_CODE",]
district_court_municipal = [ "MUNICIPAL_COURT_DISTRICT",]
district_court_county = [ "COUNTY_COURT_DISTRICT",]
district_court_appeallate = [ "COURT_OF_APPEALS",]
district_city_name = [ "CITY",]
district_city_school_district = [ "CITY_SCHOOL_DISTRICT",]
district_county_id = [ "COUNTY_ID",]
district_county_township = [ "TOWNSHIP",]
district_county_village = [ "VILLAGE",]
district_county_local_school_district = [ "LOCAL_SCHOOL_DISTRICT",]
district_county_library_district = [ "LIBRARY",]
district_county_career_center = [ "CAREER_CENTER",]
district_county_education_service_center = [ "EDU_SERVICE_CENTER_DISTRICT",]
district_county_exempted_village_school_district = [ "EXEMPTED_VILL_SCHOOL_DISTRICT",]
voter_county = [ "COUNTY",]
residence_part_number = [ "RHNUM",]
residence_part_number_suffix = [ "RDESIG",]
residence_part_street_post_type = [ "RSTSFX",]
file_origin = [ "FILE_ORIGIN",]
voter_registration_application_source = [ "APPLICATION SOURCE",]
voter_registration_permanent_absentee = [ "IS PERMANENT ABSENTEE",]
voter_registration_type = [ "VOTER TYPE",]
residence_parts_house_number = [ "HOUSENUMBER",]
residence_parts_street_name = [ "STREETNAME",]
residence_parts_unit_type = [ "UNITTYPE",]
residence_parts_unit_number = [ "UNITNUMBER",]
district_state_juristidction = [ "JURISDICTION",]
district_state_district_combo = [ "DISTRICTCOMBO",]
district_state_upper = [ "STATE SENATE",]
district_state_lower = [ "STATE ASSEMBLY",]
district_state_court_of_appeals = [ "COURT OF APPEALS",]
district_state_multijurisdictional_judge = [ "MULTI-JURISDICTIONAL JUDGE",]
district_county_name = [ "COUNTY",]
district_county_supervisory = [ "COUNTY SUPERVISORY",]
district_county_school = [ "SCHOOL",]
district_county_sanitary = [ "SANITARY",]
district_county_technical_college = [ "TECHNICAL COLLEGE",]
district_county_representational_school = [ "REPRESENTATIONAL SCHOOL",]
district_state = [ "STATE",]
district_county_district_attorney = [ "DISTRICT ATTORNEY",]
district_state_circuit_court = [ "CIRCUIT COURT",]
district_county_first_class_school = [ "FIRST CLASS SCHOOL",]
district_city_incorporation = [ "INCORPORATION",]
