name: Documentation

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install UV
        uses: astral-sh/setup-uv@v2
        with:
          version: "latest"

      - name: Cache UV dependencies
        uses: actions/cache@v4
        with:
          path: .uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies
        run: uv sync --extra docs

      - name: Build documentation
        run: |
          cd .docs
          echo "Building documentation with Sphinx..."
          uv run sphinx-build -b html source build/html
          echo "Documentation build completed successfully!"
          echo "Generated files:"
          ls -la build/html/

      - name: Upload documentation
        uses: actions/upload-pages-artifact@v3
        with:
          path: .docs/build/html

  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        continue-on-error: true

      - name: Handle Pages deployment failure
        if: steps.deployment.outcome == 'failure'
        run: |
          echo "::warning::GitHub Pages deployment failed. This is likely because:"
          echo "::warning::1. GitHub Pages is not enabled for this repository"
          echo "::warning::2. Go to repository Settings > Pages to enable GitHub Pages"
          echo "::warning::3. Select 'GitHub Actions' as the source"
          echo "::warning::Documentation was built successfully but not deployed."
          echo "::warning::Visit: https://github.com/${{ github.repository }}/settings/pages"
